//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6351071047_LTWEB_K63.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<< HEAD
    public partial class QLBANSACHEntities1 : DbContext
    {
        public QLBANSACHEntities1()
            : base("name=QLBANSACHEntities1")
=======
    public partial class QLBANSACHEntities : DbContext
    {
        public QLBANSACHEntities()
            : base("name=QLBANSACHEntities")
>>>>>>> 4cfd6914c80ba29ef1d64b8d07152bf623b3943b
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< HEAD
        public DbSet<Admin> Admins { get; set; }
=======
>>>>>>> 4cfd6914c80ba29ef1d64b8d07152bf623b3943b
        public DbSet<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }
        public DbSet<CHUDE> CHUDEs { get; set; }
        public DbSet<DONDATHANG> DONDATHANGs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<NHAXUATBAN> NHAXUATBANs { get; set; }
        public DbSet<SACH> SACHes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TACGIA> TACGIAs { get; set; }
        public DbSet<VIETSACH> VIETSACHes { get; set; }
    }
}
